# Generated by Django 3.2.2 on 2021-05-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_about_imageabout_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageabout',
            name='alt',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
