# Generated by Django 3.2.2 on 2021-06-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_imageabout_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
