# Generated by Django 3.2.2 on 2021-06-14 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cooksite', '0005_auto_20210614_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cteate_at',
            new_name='create_at',
        ),
    ]
